# Verify generated compile commands, not merely the helper implementation.
file(READ "${COMPILE_COMMANDS}" commands)
string(JSON count LENGTH "${commands}")
math(EXPR last "${count} - 1")
set(checked 0)
foreach(index RANGE 0 ${last})
    string(JSON source GET "${commands}" ${index} file)
    file(RELATIVE_PATH relative "${PROJECT_SOURCE}" "${source}")
    if(NOT relative MATCHES "^(src|tools|tests)/")
        continue()
    endif()
    string(JSON command GET "${commands}" ${index} command)
    foreach(flag IN ITEMS -Wall -Wextra)
        if(NOT command MATCHES "(^| )${flag}( |$)")
            message(FATAL_ERROR "${source} is missing ${flag}: ${command}")
        endif()
    endforeach()
    if(WARNINGS_AS_ERRORS AND NOT command MATCHES "(^| )-Werror( |$)")
        message(FATAL_ERROR "${source} is missing -Werror: ${command}")
    endif()
    math(EXPR checked "${checked} + 1")
endforeach()
if(checked EQUAL 0)
    message(FATAL_ERROR "No first-party compile commands were checked")
endif()
message(STATUS "Verified warning flags for ${checked} first-party compile commands")
